// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0k3zNF_EDauygeYWNaq3mwJ9fVlb3-ks',
    appId: '1:776313450517:web:b4d644adcedb4e67031e1c',
    messagingSenderId: '776313450517',
    projectId: 'routine-generator-1',
    authDomain: 'routine-generator-1.firebaseapp.com',
    storageBucket: 'routine-generator-1.appspot.com',
    measurementId: 'G-N5BS9V5GX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWkoEEKCLitINIiOOrIkHmDsypRfyvds',
    appId: '1:776313450517:android:9b7c050a303631f9031e1c',
    messagingSenderId: '776313450517',
    projectId: 'routine-generator-1',
    storageBucket: 'routine-generator-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXjYD7MVyx05EJfo-Tu5W-tXq5XMO8K4',
    appId: '1:776313450517:ios:3d13593df798b345031e1c',
    messagingSenderId: '776313450517',
    projectId: 'routine-generator-1',
    storageBucket: 'routine-generator-1.appspot.com',
    iosClientId: '776313450517-kqvs7invn665mjngs9ggb6bqndi621dl.apps.googleusercontent.com',
    iosBundleId: 'com.example.routine',
  );
}
